-- Execute este comando no SQL Editor do Supabase para criar a tabela

create table clients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  username text not null,
  manager text,
  days integer default 0,
  followers text,
  following text,
  posts text,
  engagement text,
  latest_post_date text
);

-- Habilitar RLS (Row Level Security) é uma boa prática, mas para começar simples e permitir leitura/escrita pública (cuidado em produção):
alter table clients enable row level security;

-- Criar política para permitir acesso público total (apenas para este MVP, depois restrinja)
create policy "Public Access" on clients
for all
using (true)
with check (true);
